baseURL = 'https://mrquantum1915.github.io/'
languageCode = 'en-us'
title = 'DARSHAN PATEL'
theme = 'custom-theme'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = true
    style = "github-dark"
    tabWidth = 4

[params]
    description = "Quantum"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Projects'
    url = '/projects'
    weight = 20
  [[menus.main]]
    name = 'Blogs'
    url = '/blogs'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    url = '/contact'
    weight = 40

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modulequeries]
    dir = ':cacheDir/modules'
    maxAge = '24h'
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1